image: node:18.15-slim

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - frontend/*/node_modules/

test:
  script:
    - npm install
    - npm test

build:
  stage: build
  script:
    - npm install # optional if ABI output path is already correctly set up via Truffle
    - npm run coco # optional if ABI output path is already correctly set up via Truffle
    - cd frontend
    - npm install
    - npm run build
  when: always
  only:
    - main
  artifacts:
    paths:
      - frontend/build

pages:
  stage: deploy
  script:
    - rm -rf public
    - mv frontend/build public
  when: always
  only:
    - main
  artifacts:
    paths:
      - public
